# GroupId: $genevalidator_sg_id # The ID of the security group. Used in cli option.
IpPermissions: # The sets of IP permissions.
- FromPort: 80  # If the protocol is TCP or UDP, this is the start of the port range.
  ToPort: 80 # If the protocol is TCP or UDP, this is the end of the port range.
  IpProtocol: 'tcp' # The IP protocol name (tcp, udp, icmp, icmpv6) or number (see Protocol Numbers).
  IpRanges: # The IPv4 ranges.
  - CidrIp: '0.0.0.0/0'  # The IPv4 CIDR range.
- FromPort: 443  # If the protocol is TCP or UDP, this is the start of the port range.
  ToPort: 443 # If the protocol is TCP or UDP, this is the end of the port range.
  IpProtocol: 'tcp' # The IP protocol name (tcp, udp, icmp, icmpv6) or number (see Protocol Numbers).  
  IpRanges: # The IPv4 ranges.
  - CidrIp: '0.0.0.0/0'  # The IPv4 CIDR range.
DryRun: false # Checks whether you have the required permissions for the action, without actually making the request, and provides an error response.
